[versions]
agp = "8.2.0"
kotlin = "2.0.20"
compose = "1.7.1"
compose-material3 = "1.3.0"
androidx-activityCompose = "1.9.2"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.13.1"
androidx-espresso-core = "3.6.0"
androidx-material = "1.12.0"
androidx-test-junit = "1.2.0"
compose-plugin = "1.7.0-beta02"
junit = "4.13.2"
navigation = "2.7.0-alpha07"
voyager = "1.1.0-alpha04"
koin = "3.5.3"
koin-compose = "1.1.2"
ktor = "2.3.12"
coroutines = "1.9.0-RC"
webview = "1.9.40-alpha01"
napier = "2.7.1"
settings = "1.1.1"
lyricist = "1.7.0"
ksp="2.0.20-1.0.25"
pods-google-maps = "8.4.0"  # IDE says not used, but _it is_ used via a .get() (why can't gradle see that?)
pods-google-mapsUtils = "4.2.2" # IDE says not used, but _it is_ used via a .get() (why can't gradle see that?)
google-MapsAndroidComposeVersion = "3.1.0"
google-PlayServicesAndroidLocation = "21.2.0"
google-PlayServicesAndroidMaps = "18.2.0"
bouquet = "1.1.2"
coil3 = "3.0.0-alpha06"
coil = "2.7.0"
kotlinx = "0.6.0"
toast="0.3.8"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenModel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-bottomSheetNavigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose"}
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin"}
koin-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin"}
koin-coroutines = { module = "io.insert-koin:koin-core-coroutines", version.ref = "koin"}
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-utils = { module = "io.ktor:ktor-utils", version.ref = "ktor" }
ktor-client-cia = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
webview = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref="webview" }
napier = {module="io.github.aakira:napier", version.ref="napier"}
setting = {module="com.russhwolf:multiplatform-settings", version.ref="settings"}
setting-noargs = {module="com.russhwolf:multiplatform-settings-no-arg", version.ref="settings"}
setting-coroutines = {module="com.russhwolf:multiplatform-settings-coroutines", version.ref="settings"}
setting-serialization = {module="com.russhwolf:multiplatform-settings-serialization", version.ref="settings"}
lyricist = { module = "cafe.adriel.lyricist:lyricist", version.ref = "lyricist" }
lyricist-processor = { module = "cafe.adriel.lyricist:lyricist-processor", version.ref = "lyricist" }
lyricist-processorXml = { module = "cafe.adriel.lyricist:lyricist-processor-xml", version.ref = "lyricist" }
google-maps-android-compose = { module = "com.google.maps.android:maps-compose", version.ref = "google-MapsAndroidComposeVersion" }
google-maps-android-compose-utils = { module = "com.google.maps.android:maps-compose-utils", version.ref = "google-MapsAndroidComposeVersion" }
google-play-services-android-location = { module = "com.google.android.gms:play-services-location", version.ref = "google-PlayServicesAndroidLocation" }
google-play-services-android-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "google-PlayServicesAndroidMaps" }
# PDF Viewer
bouquet = { module = "io.github.grizzi91:bouquet", version.ref = "bouquet" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor", version.ref = "coil3" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
coil-android = { module = "io.coil-kt.coil:coil", version.ref = "coil" }
kotlinx = {module="org.jetbrains.kotlinx:kotlinx-datetime", version.ref="kotlinx"}
toast={module="io.github.dokar3:sonner", version.ref="toast"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
com-google-devtools-ksp = {id="com.google.devtools.ksp",version.ref="ksp"}
